### ISSUE TITLE
Support for NUnit V4

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#1056]
Currently, the GUI is only capable of running NUnit V3 tests - plus V2 tests using an extension. I delayed addition of V4 support, because I thought the framework execution API was going to change. However, it remains the same and NUnit has now released version 4.1, so it's now time to add that support.

This issue is an Epic involving tasks in a number of our independent components.

- [x] TestCentric.Agent.Core TestCentric/TestCentric.Agent.Core#48
- [x] Net462PluggableAgent TestCentric/net462-pluggable-agent#44
- [x] Net60PluggableAgent TestCentric/net60-pluggable-agent#35
- [x] Net70PluggableAgent TestCentric/net70-pluggable-agent#45
- [x] Net80PluggableAgent TestCentric/net80-pluggable-agent#30
- [x] TestCentric.Engine TestCentric/testcentric-engine#195
- [x] TestCentric.GuiRunner #1057

Updating of each component's tests to run under NUnit 4 will be done at the same time.
