### ISSUE TITLE
Automate packaging and deployment

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#534]
Currently, packaging and publication of new releases is done manually on a local developer machine. The goal of this issue is to automate the entire process from creation through publication and release for both pre-release (dev) builds and final releases.

Tasks:

 - [x] Reorganize build.cake into two or three scripts using #load. Generally review structure of the script. Clean up and refactor as needed.(PR #536)
 - [x] Verify package content prior to publication. (PR #538)
 - [x] Run tests of packages prior to publication. (PR #543)
 - [x] Update assemblyInfo automatically (see also #428) (PR #546)
 - [x] Push dev builds to myget when an issue is merged successfully into master. (PR #548)
 - [x] Push rc builds to myget on merge as well. (PR #549)
 - [ ] Push packages to NuGet and chocolatey for final releases.
 - [ ] Create final releases automatically on GitHub

**Comment by CharliePoole** [comment]
@TestCentric/gui-team I'd appreciate some input on the second task listed above. What should we check about a package before releasing.

Possibilities... unzip, check (some or all) content, run a test.

Problem... Not sure how to run the gui itself in CI, since no display is available, so I'm currently only running batch tests.

Essentially, I'm asking what is needed beyond unit tests and package creation in order to release the packages automatically.

**Comment by immeraufdemhund** [comment]
hmmm.. content can change, things can break... my first assumption is to just get FileVersionInfo of the gui and check that it's the same version... but other than that I don't know of anything that I'd do cause then it would feel like i'm testing someone else's tool

**Comment by CharliePoole** [comment]
The kinds of errors I have run into are failing to include all the right files in the right directories and failing verification on chocolatey due to not meeting some requirement of theirs. So I'm not trying to test the pack command but that I gave it all the right files in the first place. OTOH, once that's correct, I suppose it's not likely to change.

Maybe I should create a small placeholder test and then add to it if the need arises. At the moment, I'm re-running a substantial portion of the unit tests, which is probably not serving any purpose except proving (indirectly) that all the right files are there.

**Comment by CharliePoole** [comment]
Probably automating running the GUI __before__ we create a package would probably be more useful to us. Right now it's possible for all unit tests to pass but the GUI crashes when you start it. I check that manually, of course, but it would be nice to have it done for me even if just on the local machine.

**Comment by CharliePoole** [comment]
@TestCentric/gui-team Does anyone know of an open-source GUI application with good testing of the full GUI or "right below the glass" as Ward Cunningham used to say?

**Comment by CharliePoole** [comment]
I separated verifying package content from running package tests in the task list. The former is easier and I'd like to get it into the 1.3.1 release.

Issue #537 is critical and I discovered it when running my new tasks for verifying package content. I'll finish work on the checks first and then fix the problems as part of #537.

**Comment by CharliePoole** [comment]
The current test runs after packaging didn't catch the fact that the net40 agent was not included in the packaging. That's because the only thing they do is expand the packages and run tests using NUnit console runner. We need a way to run the GUI itself or at least everything except the visual UI components. I'm investigating.

**Comment by CharliePoole** [comment]
Ran an experiment, adding the task "GuiTest" to what we run in AppVeyor.

Of course, the build hung, since the Gui never terminates, but the interesting thing is that no exception was thrown, which indicates to me that it may be __possible__ to run a Windows Forms app under AppVeyor. Next step will be to add some code that allows the Gui to run tests and then exit.

**Comment by CharliePoole** [comment]
Amazing! It actually works. With my temp code in place, Appveyor is able to run the app even though nothing is displayed. The result is saved and the script examines it to ensure that it ran correctly.

I'm going to add a commandline option that supports this way of running in a separate issue and then come back to this.

**Comment by immeraufdemhund** [comment]
Wooo! that is exciting!

**Comment by CharliePoole** [comment]
Yes it is! And if we can get to the point where there is near-zero overhead in doing a release, we can start doing releases whenever any new feature is ready.

**Comment by CharliePoole** [comment]
@TestCentric/gui-team I'm currently testing branch `issue-534c` with a single test run for each of the three package types. Any errors, failures or warnings are displayed in a format similar to that used by NUnit-console.

The current test is to re-run `TestCentric.Gui.Model.Tests.dll` through the GUI. I picked it as a single, fast-running test that exercises a fair amount of code. Some tests use the engine while others use a mock. The model tests target .NET Framework 4.5.

What isn't tested includes
 * Running .NET 2.0.
 * Running assemblies that call for a 32-bit process
 * Running multiple assemblies, especially with different requirements.
 * Running targets we don't yet support (of course)

It seems like all of the above are things we want to test before release. And to me, that means we want to run them automatically. OTOH I don't believe we want to run those things on every build.

So I'm looking for your ideas as to what we should run for
 * Every CI build
 * Every merge to master
 * Every release candidate
 * When we are about to publish an actual release
 * Only interactively by the developer

Some of this will be implemented in the current working branch and PR while other things may have to wait, of course. But what should be our eventual goal?

@ChrisMaddock @jnm2 Your ideas are welcome as well -- and maybe you'll be able to borrow back some of what's done here. :smiley_cat:

**Comment by CharliePoole** [comment]
@TestCentric/gui-team Thinking of using MyGet as our central release point for dev and rc builds, then pushing them upstream to nuget and chocolatey and doing the release on github. Has anyone tried that? Any comments or ideas?

**Comment by immeraufdemhund** [comment]
nope, never used it.

**Comment by CharliePoole** [comment]
I found a number of references that make it sound good.OTOH, I'm not sure if you can do the push
programatically. We'll see when we get there, and adjust accordingly.

Here's the pipeline as I'm imagining it.

1. Push to GitHub triggering a CI build
    CI build includes the package tests I've already created, maybe more. Call this CI Testing.

2. Create a PR, which triggers additional builds. Currently, this includes the CI tests. We could add more tests at this stage if desired. Call this PR Testing.

3. Approve and merge a PR. Currently, the CI tests run after the merge and if they succeed the packages are uploaded to MyGet using the `dev` suffix. If we want, we can have added testing here as well. Call this Merge Testing.

[From here on, the steps are new to us]

4. Create a release branch and trigger a CI build. All the above testing steps take place. In our current practice, we don't actually release from this branch but from master after the merge. I'm thinking of changing this and doing an RC release on MyGet. If so, we could add tests here. Call this Pre-Release Testing.

5. If we want to have further tests before moving from RC to actual release, we could add them here. Call this Release Testing. Of course, we would want users to download and try out the RC as well.

6. Push the RC upstream from MyGet to NuGet, Chocolatey and GitHub Releases. I'm not sure how to automate all this so it will take some work. Basic idea is that the same binaries are used as for the RC so we don't need to re-test at this point. Of course, if we do need to rebuild for any reason then all tests must be re-run.

So... summarizing the test stages...

 * CI Testing
 * PR Testing
 * Merge Testing => dev packages
 * Pre-release Testing => RC packages
 * Release Testing => Final release packages

Provided we don't rebuild, Release Tests are independent of the others. All the other stages are cumulateive... e.g. Merge Tests include CI tests and PR tests. At least that should be the default. We can, of course remove steps at each stage as well as add them. But it makes sense to repeat tests anytime there is a rebuild even if the code is thought to be unchanged.

@TestCentric/gui-team  This is kind of a big thing, folks, so I'd like to have your comments, which I'll incorporate as I move ahead. I feel like the ability to do releases reliably and quickly is the one thing that we are most lacking in moving ahead with features as I'd like.

Please use the stages I outlined for testing and suggest what you think should be added at each point. We can even include manual steps, although I'd want to move to automate them as soon as I could in that case.

**Comment by immeraufdemhund** [comment]
I like the steps as you've outlined, but a minor point on the branch name. Something about a merge test on a release branch kind of bugs me. it's minor so I won't fight for it, but I feel like the pre-release should be on the release branch. I would think a feature branch would be suitable for the merge testing and dev.

Everything else sounds awesome! I normally don't subscribe to RC and Dev things anymore after I got bit from visual studio but this would be so much easier to downgrade if needed.

**Comment by CharliePoole** [comment]
@immeraufdemhund I'm not 100% sure myself as to what we should do on the release branch and what we should do on master. NUnit itself has gone back and forth on this over the years.

Currently, we don't release until __after__ merging the release branch to master and that step is entirely manual. If we are able to simply promote a release candidate and push it from MyGet to NuGet/Chocolatey/etc. without rebuilding, that seems to me like a big advantage and it might mean that merging in the release branch to master then becomes a bit of a non-event.

But, as stated, I'm unsure and I think we can hold the alternative options in our minds until we get a bit further along.

Are you OK with the latest PR on the build scripts? I added a few inline comments of my own on GitHub to explain some of what I'm doing.

**Comment by CharliePoole** [comment]
If you are following this issue and wondering about the large number of PRs for a relatively small change, it's because there is no easy way to simulate running and publishing on AppVeyor. So I create small PRs and watch what happens when they run in CI and finally merge. 

After I get RC releases to build, I'll even be doing a fake RC release on MyGet, which I will then immediately delete.

**Comment by CharliePoole** [comment]
Splitting this issue to handle only packaging and deployment. Automation of final releases will be handled by a separate issue. I'm doing this so as to fully exercise what is done so far to create and test a release branch, release it manually and merge to master. This will help identify what more is needed for full release automation.
