### ISSUE TITLE
Merge features of the experimental GUI into the 2.0 standard GUI

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#732]
The Experimental GUI will be removed in the final 2.0 Release and most of its features added  to the standard GUI. This issue covers the overall process. It's basically an Epic. Further issues (Stories) will be created to track each individual change.

Once all the individual stories are completed, this issue will be responsible for removing all remnants of the Expermental GUI from the repository.

**Comment by CharliePoole** [comment]
This is a list of the individual experimental features, which are to be moved to the 2.0 GUI. Issue and PR references will be added as they are created. New items may be added as the work progresses.

- [ ] Startup (AppEntry code)
- [ ] Status Bar implementation
- [ ] Progress Bar implementation

**Comment by CharliePoole** [comment]
This issue, when completed will leave some duplicate information displayed in the GUI, to be resolved separately, as well as a number of issues created under the experimental GUI, which will still need to be resolved before the next release.
