### ISSUE TITLE
Standardize testing of extensions

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#971]
Currently, extensions are tested in three places:

1. In the extension project itself
2. In the TestCentric Engine project
3. In the TestCentric Gui project

The intent of this issue is to modify where we do the testing, as follows:

1. Expand the testing of each extension within it's own project to include all cases found elsewhere.
2. Eliminate testing of most extensions in the Engine and GUI projects.
3. Continue to test any built-in agents (which are not extensions) within the engine and gui projects
4. Any extensions which are distributed along with the engine or gui will be retested as a part of each project.

Pluggable Agents possibly needing expanded testing:
- [x] Net20PluggableAgent - **Review shows none needed**
- [x] NetCore21PluggableAgent - **Review shows none needed**
- [x] TestCentric/netcore31-pluggable-agent#2
- [x] TestCentric/net50-pluggable-agent#2
- [x] TestCentric/net80-pluggable-agent#4

Projects from which pluggable agent tests should be dropped
- [x] TestCentric/testcentric-engine#105
- [x] #972
